### ISSUE TITLE
How to attach payload?

### ISSUE THREAD

**Issue by robcarey** [besciualex/FacebookPixelConversionApi#1]
Can you provide any examples on how to attach payload?

**Comment by besciualex** [comment]
> Can you provide any examples on how to attach payload?

So here is the payload builder:
https://developers.facebook.com/docs/marketing-api/conversions-api/payload-helper/

Just create a new public method in FacebookConversionApiEvent class.

`

    public function setCustomPayload(string $key_name, string $value ){

        $this->event["custom_data"][$key_name] = $value;

    }
`

then call it like this:

`

    $fb_event = new FacebookConversionApiEvent(FacebookEvents::Lead);  

    $fb_event->setEmail($_POST['email']);  

    $fb_event->setCustomPayload('github_name', 'robcarey');  

    $fb_event->send();
`

**Comment by robcarey** [comment]
@besciualex spectacular.  Thanks for your guidance.  Much appreciated!
